### ISSUE TITLE
Release dapr-python v0.5.0a0

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#40]
## Describe the proposal

This is the release plan to ship dapr-python v0.5.0b.

* Package name: dapr
   - python-sdk includes actor sdk implemenation with the generated proto client so that it makes sense to rename from `dapr-clients` to `dapr`
* Package version: 0.5.0b
* Release work items.
   - [x] Merge features/actor to master
   - [x] Set up CI/CD
   - [x] Improve README.md
   - [ ] validate with dotnet-sdk
   - [ ] Release dapr-python 0.5.0a

**Comment by youngbupark** [comment]
@msfussell @orizohar @yaron2 @amanbha Please review this release plan and give me any feedbacks. 

cc/ @mchmarny

**Comment by orizohar** [comment]
A couple of thoughts:
1. For the naming `dapr-python`, if this is a python package, is the suffix redundant? should we perhaps just call it `dapr` or `dapr-sdk`?
2. As discussed offline - since actors are not common in the Python world we need to make sure we provide good links to what is the Actor model for python devs who are new to this.

**Comment by youngbupark** [comment]
> A couple of thoughts:
> 
> 1. For the naming `dapr-python`, if this is a python package, is the suffix redundant? should we perhaps just call it `dapr` or `dapr-sdk`?

We can call `dapr` I will update it on the plan. 

> 2. As discussed offline - since actors are not common in the Python world we need to make sure we provide good links to what is the Actor model for python devs who are new to this.

yeah https://github.com/dapr/python-sdk/issues/37 will add the link.

**Comment by amanbha** [comment]
@youngbupark `dapr` LGTM

**Comment by youngbupark** [comment]
Merged features/actor to master now.

**Comment by youngbupark** [comment]
Every build will be published to [dapr-dev](https://pypi.org/project/dapr-dev/). So anyone can install the latest build.

Release build will be [dapr](https://pypi.org/project/dapr). the official build will be uploaded to this repo.
